export const GET_USER_POST = 'GET_USER_POST'

export const POST_USERPOST_REQUEST="POST_USERPOST_REQUEST";
export const POST_USERPOST_SUCCESS="POST_USERPOST__SUCCESS";
export const POST_USERPOST_FAIL="POST_USERPOST_FAIL";